### ISSUE TITLE
How to trigger html-beautify in chain loader?

### ISSUE THREAD

**Issue by redstrike** [tomaszczechowski/jsbeautify-loader#3]
I want to read a nunjucks template file via file-loader, then compile it to html and html-beautify it. How can I accomplish this with jsbeautify-loader? By default, the loader can only handle js files, so the beautified result is a mess.

**Comment by tomaszczechowski** [comment]
Hey

jsbeautify handles a HTML files as well:

``` javascript
jsBeautify: {
    "html": {
      "allowed_file_extensions": ["html", "xhtml", "shtml", "xml", "svg"],
      "indent_size": 2
    }
},
```

other options you can find here https://github.com/beautify-web/js-beautify

verify whether it's sufficient for you otherwise let me know

**Comment by redstrike** [comment]
Hi @tomaszczechowski,

Below is a part of my webpack.config.js:

``` js
module: {
  loaders: [
    { test: /\.tsx?$/, loader: 'ts-loader' },
    {
      test: /\.njk$/,
      loader: `file?name=[name].html!jsbeautify-loader!nunjucks-html?${JSON.stringify({ 'searchPaths': ['./src/njk/']})}`
    }
  ],
},
```

I want to use webpack to watch file changes, compile my nunjucks template to HTML and beautify it by using jsbeautify-loader, then save the beatified HTML content to a file via file-loader.
At the moment, jsbeautify-loader cannot detect the HTML content, so it processes the HTML content to a mess.

Does jsbeautify-loader support this use case?

**Comment by tomaszczechowski** [comment]
Hey

Ok, tomorrow I should release new version of jsbeautify-loader which would handle your use case.

**Comment by tomaszczechowski** [comment]
Hey 

Please check version 0.3.0 which I have already released. 

I tested it using below configuration and seems to work fine. Please note that I added "**type**" parameter into loader definition:

``` javascript
module.exports = {
  jsBeautify: {
    "js": {
      "allowed_file_extensions": ["js"], // optional parameter in case allowed file extension is the same as name of parent property.
      "indent_size": 2,
      "indent_char": " ",
      "space_after_anon_function": true
    },
    "html": {
      "allowed_file_extensions": ["html", "xhtml", "shtml", "xml", "svg"],
      "indent_size": 2
    }
  },

  module: {
    loaders: [
      {
        test: /\.njk$/,
        loader: "file?name=template.html!./index?type=html!nunjucks-html"
      }
    ]
  }
};
```

if you still experience any issue let me know 😄
